using System;
using System.Collections.Generic;
using System.Text;

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


//namespace Project_Euler.Problems
//{
//    public class Problem2
//    {
//        public static void Main()
//        {
//            // a+b=c b+c=d
//            int a = 1;
//            int b = 2;
//            int max = 4000000;
//            int sum = 2;
//       //     Console.WriteLine(b);
//            for (; a + b < max;)
//            {
//                int c = a + b;
//                a = b;
//                b = c;
//                if ((c % 2) == 0)
//                {
//                    sum = sum + c;
//                    // Console.WriteLine(c);                    
//                }
//            }
//            Console.WriteLine(sum);
//            Console.ReadLine();
//        }
//    }
//}
